# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '7.0'
target 'PaoBu' do
    pod 'Mantle', '~> 1.5.5'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'SVPullToRefresh', '~> 0.4.1'
    pod 'SVProgressHUD', '~> 0.9'
    #pod 'CocoaLumberjack', '~> 1.9.2'
    pod 'BlocksKit', '~> 2.2.5'
    pod 'FCFileManager', '~> 1.0.12'
    pod 'FMDB', '~> 2.5'
    pod 'LKDBHelper', '~> 2.1.4'
    pod 'IQKeyboardManager', '~> 3.2.0.3'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'CRNavigationController', '~> 1.1'
    pod 'AFNetworking', '~> 2.4.1'
    pod 'JGProgressHUD', '~> 1.2.7'
    pod 'TSMessages', '~> 0.9.12'
    pod 'HexColors', '~> 2.2.1'
    pod 'ActionSheetPicker-3.0', '~> 1.3.12'
    pod 'XMLDictionary', '~> 1.4'
    pod 'EGOCache', '~> 2.1.3'
    pod 'Masonry', '~> 0.5.3'
    pod 'CSNPlaceholderTextView', '~> 0.0.4'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'Reachability', '~> 3.2'
    pod 'INTULocationManager', '~> 1.2.0'
    #pod 'RCLocationManager', '~> 0.1'
    #pod 'FLAnimatedImage', '~> 1.0.7'
    pod 'INTUGroupedArray','~> 1.1.1'
    #pod 'DebugView'
    pod 'JSCustomBadge','~> 1.0.1'
    pod 'ZipArchive'
    #pod 'RMStore', '~> 0.7.1'
    pod 'DTCoreText', '~> 1.6.16'
    pod 'DACircularProgress', '~> 2.3.1'
    pod 'PSTCollectionView', '~> 1.2.3'
    pod 'OpenUDID'
end
